# -*- coding: utf-8 -*-
"""
Created on Mon Nov  2 09:20:59 2020

@author: kaktu
"""
písmena = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
zpráva = "IVKJXVOFPWTGVDIAJMHVXZOVDIAJMHVXZWTGJPWJCVOVDIAJMHVXZWTGVWPCOJWTGJIVKJXVOFPPWJCVQNZXCIJKJQNOVGJNFMUZIDVWZUIDIZKJQNOVGJIDXXJEZNOQIDWTGUDQJOVUDQJOWTGNQZOGJGDYDOJNQZOGJQZOHZNQDODVOHVEZIZKJCGODGVJYWJCVWTGKJNGVIXGJQZFEHZIZHEVIOZIKMDNZGKMJOJVWTQTYVGNQZYZXOQDJOJHNQZOGZVWTQNDXCIDPQZMDGDNFMUZIZCJEVINVHIZWTGODHNQZOGZHVGZKMDNZGVWTJOJHNQZOGZQTYVGNQZYZXOQDWTGJOPKMVQZNQZOGJFOZMZJNQZXPEZFVUYZCJXGJQZFVOJKMDXCVUZGJYJNQZOVIVNQZOZWTGNQZONFMUZIZEKJQNOVGVGZNQZOCJIZKJUIVGKMDNZGYJNQZCJQGVNOIDCJVGZEZCJQGVNOIDCJIZKMDEVGDOZHKVFFOZMDCJKMDEVGDVQZMDQEZCJEHZIJYVGHJXNOVONZWJUDHDYZOHD"


for písmeno in range(len(písmena)):
   přeloženo = ""
   for symbol in zpráva:
      if symbol in písmena:
         číslo = písmena.find(symbol)
         číslo = číslo - písmeno
         if číslo < 0:
            číslo = číslo + len(písmena)
         přeloženo = přeloženo + písmena[číslo]
      else:
         přeloženo = přeloženo + symbol
   print(f"úprava {písmeno}: {přeloženo}")